apiVersion : apps/v1
kind: Deployment
metadata:
  name: akhileshgopaldemoapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhileshgopaldemoapp
  template:
    metadata:
      labels:
        app: akhileshgopaldemoapp 
    spec:
      containers:
        - name: akhileshgopaldemoapp 
          image: akhileshrepo.azurecr.io/akhileshgopaldemoapp
          ports:
          - containerPort: 80